// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Folder struct {
	FolderID string `json:"folderId"`
	Name     string `json:"name"`
	OwnerID  string `json:"ownerId"`
}

type Mutation struct {
}

type Notes struct {
	NoteID   string `json:"noteId"`
	Title    string `json:"title"`
	Body     string `json:"body"`
	FolderID string `json:"folderId"`
	OwnerID  string `json:"ownerId"`
}

type Query struct {
}

type Team struct {
	TeamID      string  `json:"teamId"`
	TeamName    string  `json:"teamName"`
	TeamMembers []*User `json:"teamMembers"`
	TeamManager []*User `json:"teamManager"`
}

type User struct {
	UserID       string `json:"userId"`
	UserName     string `json:"userName"`
	Email        string `json:"email"`
	Role         string `json:"role"`
	PasswordHash string `json:"passwordHash"`
}
